services:
  db:
    image: postgres:latest
    container_name: postgres_dbt
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    
  pgadmin:
    image: elestio/pgadmin
    container_name: pgadmin_dbt
    restart: always
    ports: 
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL} 
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD} 
      volumes: pgadmin_data:/var/lib/pgadmin
    
volumes:
  pg_data:
  pgadmin_data: